# fly.toml app configuration file generated for song-discovery on 2023-04-27T00:44:51-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "song-discovery"
kill_signal = "SIGINT"
kill_timeout = 5
mounts = []
primary_region = "dfw"
processes = []

[build]
  builder = "paketobuildpacks/builder:base"

[env]
  PORT = "8080"

[[services]]
  internal_port = 8080
  processes = ["app"]
  protocol = "tcp"
  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"

  [[services.ports]]
    force_https = true
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443
